language: java
language: node_js
node_js:
 - 12

branches:
  only:
  - testIntegration

env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

#addons:
#  sonarcloud:
#    organization: "khptif" # the key of the org you chose at step #3
#    token:
#      secure: ${SONAR_TOKEN} # encrypted value of your token
 
cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules


jobs:
  include:
    - stage : Build
      script: 
      - ./travisScripts/buildtestK.sh
      - cd testIntegration
      - ./script.sh
      - cd ..
      - ./travisScripts/buildPushServices.sh
#      - sonar-scanner
      
      after_success:
      - ./travisScripts/buildAfterSuccess.sh
      
